Main.out: main.o Pieza.o Rey.o Torre.o Caballo.o Reina.o Alfil.o
	g++ main.o Pieza.o Rey.o Torre.o Caballo.o Reina.o Alfil.o -o main.out



Main.o: main.cpp Pieza.cpp Rey.cpp Torre.cpp Caballo.cpp Reina.cpp Alfil.cpp

	g++ main.cpp

